"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, use environment variable: os.environ.get('SECRET_KEY')
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-ex=1jz(vh14@!b$xdyt*ztqff^7+&i7pk%=f^u39aqyhw=@u&_')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production via environment variable
# This prevents exposing sensitive error information
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS: List of host/domain names that this Django site can serve
# In production, set this to your actual domain names
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf.apps.BookshelfConfig',
    'relationship_app.apps.RelationshipAppConfig',
    'authtools.apps.AuthtoolsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Provides security enhancements
    'bookshelf.middleware.ContentSecurityPolicyMiddleware',  # Custom CSP middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection for forms
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # X-Frame-Options header
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# SECURITY SETTINGS
# ============================================================================
# These settings enhance the security of your Django application by protecting
# against common vulnerabilities like XSS, CSRF, clickjacking, and more.

# ----------------------------------------------------------------------------
# XSS (Cross-Site Scripting) Protection
# ----------------------------------------------------------------------------
# SECURE_BROWSER_XSS_FILTER: Enables browser's XSS filtering
# When True, adds the X-XSS-Protection: 1; mode=block header to responses
# This enables the browser's built-in XSS protection mechanism
# Note: Modern browsers have this enabled by default, but this ensures compatibility
SECURE_BROWSER_XSS_FILTER = True

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents browsers from MIME-sniffing
# When True, adds the X-Content-Type-Options: nosniff header
# This prevents browsers from interpreting files as a different MIME type
# Protects against MIME-sniffing attacks that could execute malicious scripts
SECURE_CONTENT_TYPE_NOSNIFF = True

# X_FRAME_OPTIONS: Prevents clickjacking attacks by controlling whether
# the site can be embedded in frames/iframes
# Options:
#   - 'DENY': Completely prevents framing (most secure)
#   - 'SAMEORIGIN': Allows framing only from same origin
#   - 'ALLOW-FROM': Allows framing from specified origin (deprecated)
# Set to 'DENY' for maximum security against clickjacking attacks
X_FRAME_OPTIONS = 'DENY'  # Most secure: completely prevents framing

# ----------------------------------------------------------------------------
# CSRF (Cross-Site Request Forgery) Protection
# ----------------------------------------------------------------------------
# CSRF_COOKIE_SECURE: Ensures CSRF cookies are only sent over HTTPS
# When True, CSRF cookies are only transmitted over secure HTTPS connections
# This prevents interception of CSRF tokens over unencrypted connections
# Set to True in production when using HTTPS
# Set via environment variable: CSRF_COOKIE_SECURE=True
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', str(not DEBUG)) == 'True'

# CSRF_COOKIE_HTTPONLY: Prevents JavaScript access to CSRF cookie
# This helps prevent XSS attacks from stealing the CSRF token
CSRF_COOKIE_HTTPONLY = True

# CSRF_COOKIE_SAMESITE: Controls when CSRF cookie is sent
# Options: 'Strict', 'Lax', 'None'
# 'Lax' is a good balance between security and usability
CSRF_COOKIE_SAMESITE = 'Lax'

# CSRF_TRUSTED_ORIGINS: List of trusted origins for CSRF protection
# Add your production domain here when deploying
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# ----------------------------------------------------------------------------
# Session Security
# ----------------------------------------------------------------------------
# SESSION_COOKIE_SECURE: Ensures session cookies are only sent over HTTPS
# When True, session cookies are only transmitted over secure HTTPS connections
# This prevents session hijacking attacks over unencrypted connections
# Set to True in production when using HTTPS
# Set via environment variable: SESSION_COOKIE_SECURE=True
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', str(not DEBUG)) == 'True'

# SESSION_COOKIE_HTTPONLY: Prevents JavaScript access to session cookie
# This helps prevent XSS attacks from stealing session data
SESSION_COOKIE_HTTPONLY = True

# SESSION_COOKIE_SAMESITE: Controls when session cookie is sent
# 'Lax' is a good balance between security and usability
SESSION_COOKIE_SAMESITE = 'Lax'

# SESSION_COOKIE_AGE: Session timeout in seconds (default: 2 weeks)
# Consider reducing this for more sensitive applications
SESSION_COOKIE_AGE = 1209600  # 2 weeks

# ----------------------------------------------------------------------------
# HTTPS and SSL Settings (for production)
# ----------------------------------------------------------------------------
# These settings enforce HTTPS connections and protect against various attacks.
# IMPORTANT: Only enable these in production after setting up SSL/TLS certificates.

# SECURE_SSL_REDIRECT: Redirects all HTTP requests to HTTPS
# When True, Django automatically redirects all non-HTTPS requests to HTTPS
# This ensures all communication is encrypted and protects against man-in-the-middle attacks
# Set via environment variable: SECURE_SSL_REDIRECT=True
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'

# SECURE_HSTS_SECONDS: HTTP Strict Transport Security (HSTS) duration in seconds
# HSTS tells browsers to only access the site via HTTPS for the specified time period
# This prevents protocol downgrade attacks and cookie hijacking
# Recommended value: 31536000 (1 year) for production
# Set via environment variable: SECURE_HSTS_SECONDS=31536000
# WARNING: Once set, browsers will cache this policy. Start with a small value for testing.
hsts_seconds = os.environ.get('SECURE_HSTS_SECONDS', '0')
SECURE_HSTS_SECONDS = int(hsts_seconds) if hsts_seconds.isdigit() else 0

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Apply HSTS to all subdomains
# When True, HSTS policy applies to all subdomains of your domain
# This provides comprehensive protection across your entire domain
# Set via environment variable: SECURE_HSTS_INCLUDE_SUBDOMAINS=True
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'

# SECURE_HSTS_PRELOAD: Enable HSTS preload
# When True, allows your domain to be submitted to browser HSTS preload lists
# Preloaded domains are hardcoded into browsers, providing even stronger protection
# Only enable after thoroughly testing your HTTPS setup
# Set via environment variable: SECURE_HSTS_PRELOAD=True
# More info: https://hstspreload.org/
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'

# ----------------------------------------------------------------------------
# Content Security Policy (CSP)
# ----------------------------------------------------------------------------
# CSP helps prevent XSS attacks by specifying which domains can load resources
# We'll implement this via middleware (see middleware.py or custom middleware)

# CSP settings (if using django-csp package, uncomment and configure):
# CSP_DEFAULT_SRC = ["'self'"]
# CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'"]  # Remove 'unsafe-inline' in production
# CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]  # Remove 'unsafe-inline' in production
# CSP_IMG_SRC = ["'self'", "data:", "https:"]
# CSP_FONT_SRC = ["'self'"]
# CSP_CONNECT_SRC = ["'self'"]

# For now, we'll set CSP headers manually in a custom middleware
# See bookshelf/middleware.py for implementation

# ----------------------------------------------------------------------------
# Additional Security Headers
# ----------------------------------------------------------------------------
# SECURE_REFERRER_POLICY: Controls Referer header
# Options: 'no-referrer', 'no-referrer-when-downgrade', 'origin', etc.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ----------------------------------------------------------------------------
# Password Security
# ----------------------------------------------------------------------------
# Password validators are already configured above
# Additional settings:
# PASSWORD_RESET_TIMEOUT: Time in seconds for password reset links (default: 259200 = 3 days)
PASSWORD_RESET_TIMEOUT = 259200

# ----------------------------------------------------------------------------
# File Upload Security
# ----------------------------------------------------------------------------
# DATA_UPLOAD_MAX_MEMORY_SIZE: Maximum size for file uploads (default: 2.5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB

# FILE_UPLOAD_MAX_MEMORY_SIZE: Maximum size for in-memory file uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB

# FILE_UPLOAD_PERMISSIONS: File permissions for uploaded files (0o644 = rw-r--r--)
FILE_UPLOAD_PERMISSIONS = 0o644

# ----------------------------------------------------------------------------
# Security Notes for Production Deployment
# ----------------------------------------------------------------------------
# Before deploying to production, ensure:
# 1. DEBUG = False
# 2. Set SECRET_KEY via environment variable
# 3. Configure ALLOWED_HOSTS with your domain
# 4. Enable HTTPS and set SECURE_SSL_REDIRECT = True
# 5. Set CSRF_COOKIE_SECURE = True
# 6. Set SESSION_COOKIE_SECURE = True
# 7. Configure SECURE_HSTS_SECONDS
# 8. Remove 'unsafe-inline' from CSP directives
# 9. Use a proper web server (nginx, Apache) in front of Django
# 10. Keep Django and all dependencies updated
