# Generated by Django 5.2.7 on 2025-10-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publiction_year',
            field=models.IntegerField(default=1949),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=1949, max_length=200),
            preserve_default=False,
        ),
    ]
