# Generated by Django 5.2.7 on 2025-10-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_book_author_book_publiction_year_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publiction_year',
            new_name='publication_year',
        ),
    ]
